cargo-features = ["strip"]

[package]
name = "r-display"
version = "0.1.0"
authors = ["Moritz Moeller <virtualritz@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
c_vec = "1.3.3"
exr = "0.8.0"
ndspy-sys = { version = "0.1.1", features = ["download_3delight_lib"] }
#png = "0.16.4"
oidn = { path = "../oidn-rs" } #"1.1.0"
cgmath = "0.17.0"

[profile.release]
rpath = false
lto = "on"
opt-level = 3
codegen-units = 1
strip = "symbols"
panic = "abort"

[profile.dev]
rpath = false
