cargo-features = ["strip"]

[package]
name = "r-display"
version = "0.3.0"
authors = ["Moritz Moeller <virtualritz@protonmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
cgmath = "0.17.0"
c_vec = "1.3.3"
exr = "0.8.0"
ndspy-sys = "0.1.4"
oidn = "1.2.0"
rayon = "1.4.0"

[dev-dependencies]
nsi = "0.5.3"
polyhedron-ops = { path = "../crates/polyhedron-ops" }

[profile.release]
rpath = false
lto = "on"
opt-level = 3
codegen-units = 1
strip = "symbols"
panic = "abort"

[profile.dev]
rpath = false
